apiVersion: apps/v1
kind: Deployment
metadata:
  name: stemcell-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: stemcell-controller-manager
  template:
    metadata:
      labels:
        control-plane: stemcell-controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: controller:latest
          args:
            - --leader-elect
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
